[package]
name = "school-of-life-portal"
version = "0.0.0"
description = "A textbook-based eLearning application."
authors = [
	"School of Life Project",
]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [
] }

[dependencies]
tauri = { version = "1", features = [
	"fs-read-file",
] }
serde = { version = "1", features = [
	"derive",
] }
serde_json = "1"
uuid = { version = "1.9.1", features = [
	"v4",
	"serde",
] }
toml = "0.8.14"
tokio = { version = "1.38.0", features = [
	"fs",
] }
open = "5.2.0"
dirs-next = "2.0.0"
advisory-lock = "0.3.0"
anyhow = "1.0.86"
thiserror = "1.0.61"
serde-error = "0.1.2"

[features]
custom-protocol = [
	"tauri/custom-protocol",
]

[profile.release]
panic         = "abort"
codegen-units = 1
lto           = true
strip         = true
