[package]
name = "school-of-life-portal"
version = "0.0.0"
description = "A textbook-based eLearning application."
authors = [
	"School of Life Project",
]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [
] }

[dependencies]
tauri = { version = "1", features = [
	"protocol-asset",
] }
serde = { version = "1", features = [
	"derive",
] }
uuid = { version = "1.10.0", features = [
	"v4",
	"serde",
] }
toml = "0.8.14"
tokio = { version = "1.38.0", features = [
	"fs",
] }
open = "5.3.0"
dirs-next = "2.0.0"
advisory-lock = "0.3.0"
anyhow = "1.0.86"
thiserror = "1.0.62"
futures-util = "0.3.30"
chrono = { version = "0.4.38", default-features = false, features = [
	"std",
	"clock",
	"serde",
] }
serde_with = "3.8.3"
zip = { version = "2.1.3", default-features = false, features = [
	"bzip2",
	"deflate",
	"deflate64",
	"lzma",
	"zstd",
] }
layout-rs = "0.1.2"
native_db = "0.7.1"
native_model = "0.4.19"

[features]
custom-protocol = [
	"tauri/custom-protocol",
]

[profile.release]
panic         = "abort"
codegen-units = 1
lto           = true
strip         = true
